[blue_loadout]
  team_color_id = 7
  custom_color_id = 85
  car_id = 3451
  decal_id = 3476
  wheels_id = 3899
  boost_id = 52
  antenna_id = 0
  hat_id = 5111
  paint_finish_id = 272
  custom_finish_id = 274
  engine_audio_id = 1873
  trails_id = 1974
  goal_explosion_id = 3071
  [blue_loadout.paint]
    car_paint_id = 0
    decal_paint_id = 0
    wheels_paint_id = 0
    boost_paint_id = 10
    antenna_paint_id = 0
    hat_paint_id = 0
    trails_paint_id = 5
    goal_explosion_paint_id = 10

[orange_loadout]
  team_color_id = 7
  custom_color_id = 76
  car_id = 3451
  decal_id = 3476
  wheels_id = 3899
  boost_id = 52
  antenna_id = 0
  hat_id = 5111
  paint_finish_id = 272
  custom_finish_id = 274
  engine_audio_id = 1873
  trails_id = 1974
  goal_explosion_id = 3071
  [orange_loadout.paint]
    car_paint_id = 0
    decal_paint_id = 0
    wheels_paint_id = 0
    boost_paint_id = 10
    antenna_paint_id = 0
    hat_paint_id = 0
    trails_paint_id = 5
    goal_explosion_paint_id = 10
